### ISSUE TITLE
ensure light-codegen can be compile on both jdk8 and jdk11

### ISSUE THREAD

**Issue by 0x6e6562** [networknt/light-codegen#159] opened 2018-06-21 12:42 UTC
Using b3f2837 doing 

`mvn clean install -DskipTests`

produces this error:

```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Parent POM 1.5.15 .................................. SUCCESS [  1.954 s]
[INFO] codegen-core ....................................... FAILURE [  0.986 s]
[INFO] light-rest-4j-generator ............................ SKIPPED
[INFO] light-hybrid-4j-generator .......................... SKIPPED
[INFO] light-graphql-4j-generator ......................... SKIPPED
[INFO] light-eventuate-4j-generator ....................... SKIPPED
[INFO] codegen-fwk ........................................ SKIPPED
[INFO] codegen-cli ........................................ SKIPPED
[INFO] codegen-web 1.5.15 ................................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.011 s
[INFO] Finished at: 2018-06-21T13:31:23+01:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project codegen-core: Fatal error compiling: CompilerException: InvocationTargetException: java.nio.file.NotDirectoryException: /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/lib/modules -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.6.1:compile (default-compile) on project codegen-core: Fatal error compiling
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:213)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:956)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Fatal error compiling
```

It looks like this the maven build expects this node to be a directory (locally this appears to be a file):

```
ls -lh /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/lib/modules`
-rw-r--r--  1 root  wheel   179M 27 Mar 02:16 /Library/Java/JavaVirtualMachines/jdk-10.0.1.jdk/Contents/Home/lib/modules
```

This is using mvn 3.5.3.

Has anybody noticed this issue on this project or is a more general maven problem?

**Comment by 0x6e6562** [comment] 2018-06-21 12:54
I managed to build this using JDK 8 - is it maybe that JDK 9/10 are not yet supported?

**Comment by vaishnavipanchal23** [comment] 2019-04-08 21:09
@stevehu I am also facing the same issue (using Oracle JDK 10), when can we expect an upgrade for this?

**Comment by stevehu** [comment] 2019-04-08 22:16
I have reopened the issue to support JDK 9 to 11 in the jdk11 branch. Like other light-4j repositories, we are going to support jdk8 in the master branch and jdk9-11 in the jdk11 branch. I am marking this as help wanted and hope someone going to pick it up. Thanks a lot for bringing it up.

**Comment by stevehu** [comment] 2019-04-10 20:35
It looks like the problem is caused by Google error-prone. I have made some update and the master branch can be compile by both jdk8 and jdk11 now.

**Closed** 2019-04-10 20:38 UTC
Labels: enhancement, help wanted

**Comment by stevehu** [comment] 2019-04-10 20:39
![](https://github.trello.services/images/mini-trello-icon.png) [ensure light-codegen can be compile on both jdk8 and jdk11](https://trello.com/c/sYDxxARF/164-ensure-light-codegen-can-be-compile-on-both-jdk8-and-jdk11)
